"""Generate clowns_defines.asm: memory map, I/O ports, RAM variables and
constants for clowns_program_rom.asm, from the tables in notes.py."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import notes

OUT = os.path.join(HERE, "clowns_defines.asm")

HEADER = """\
;Clowns (Midway, 1978) - hardware map, RAM variables and equates for
;clowns_program_rom.asm (MAME 'clowns', rev. 2).
;No original source is known: all names were given for this disassembly.
;Hardware notes follow the MAME driver mw8080bw.cpp.
;Generated by disasm/emit_defines.py; every symbol the program listing uses is here.
"""

def banner(title):
    return ";" + "-" * 34 + "[ " + title + " ]" + "-" * 34

def alias(name, value, comment):
    return (".alias %-16s $%0*X" % (name, 2 if value < 0x100 else 4, value)).ljust(32) + " ;" + comment

def main():
    out = [HEADER]
    out.append(banner("Memory map"))
    out += [alias(*e) for e in notes.MEMORY_MAP]
    out += ["", banner("Input ports"), ";8080 I/O space (IN). Port numbers repeat every 4."]
    out += [alias(*e) for e in notes.PORTS_IN]
    out += ["", banner("Output ports"), ";8080 I/O space (OUT)."]
    out += [alias(*e) for e in notes.PORTS_OUT]
    groups = [("Work RAM: script, scores, timers", 0x2000, 0x2040),
              ("Work RAM: balloon rows", 0x2040, 0x2118),
              ("Work RAM: seesaw, players, clown objects", 0x2118, 0x2200),
              ("Work RAM: text buffer and game state", 0x2200, 0x2400)]
    for title, lo, hi in groups:
        out += ["", banner(title)]
        for a, name, size, comment in notes.RAM:
            if lo <= a < hi:
                if size > 2:
                    comment = "%d bytes. %s" % (size, comment)
                elif size == 2:
                    comment = "2 bytes. " + comment
                out.append(alias(name, a, comment))
    out += ["", banner("Constants")]
    for title, entries in notes.CONSTANTS:
        out.append(";" + title)
        out += [alias(*e) for e in entries]
    with open(OUT, "w", newline="\n") as fp:
        fp.write("\n".join(out) + "\n")
    print("wrote %s (%d symbols)" % (os.path.basename(OUT), sum(1 for l in out if l.startswith(".alias"))))

if __name__ == "__main__":
    main()
