#!/usr/bin/env python3
"""Generate the ROM image and the ROM label addresses the Clowns port links.

Inputs (both written by disasm/gen_from_roms.py - never hand-transcribed):
  ../disasm/build/clowns_cpu.bin        the 6K program ROM image
  ../disasm/build/program_refs.json     the named labels of the listing

Outputs (c_src/):
  progrom.c/.h    program ROM $0000-$17FF  (progrom[addr])
  rom_labels.h    #define R_Name 0xADDR for every named label of the listing,
                  so translated code reads ROM tables at their ROM addresses by
                  name (ROM(R_NoteTable + 2 * n)) and never retypes them

Rerun:  python c_src/tools/gen_roms.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CSRC = os.path.normpath(os.path.join(HERE, ".."))
ROOT = os.path.normpath(os.path.join(CSRC, ".."))
IMAGE = os.path.join(ROOT, "disasm", "build", "clowns_cpu.bin")
REFS = os.path.join(ROOT, "disasm", "build", "program_refs.json")


def need(path):
    if not os.path.exists(path):
        sys.exit("gen_roms: missing %s (run disasm/gen_from_roms.py first)" % path)
    return path


def main():
    with open(need(IMAGE), "rb") as f:
        data = f.read()
    with open(need(REFS)) as f:
        labels = json.load(f)["labels"]
    with open(os.path.join(CSRC, "progrom.h"), "w", encoding="utf-8", newline="\n") as f:
        f.write("/* progrom.h - GENERATED by c_src/tools/gen_roms.py - do not edit. */\n"
                "#ifndef PROGROM_H\n#define PROGROM_H\n#include <stdint.h>\n"
                "#define PROGROM_SIZE 0x%04X\n"
                "extern const uint8_t progrom[0x%04X]; /* program ROM $0000-$%04X */\n#endif\n"
                % (len(data), len(data), len(data) - 1))
    with open(os.path.join(CSRC, "progrom.c"), "w", encoding="utf-8", newline="\n") as f:
        f.write("/* progrom.c - GENERATED by c_src/tools/gen_roms.py from\n"
                " * ../disasm/build/clowns_cpu.bin - do not edit.\n"
                " * Clowns program ROM, CPU $0000-$%04X. */\n" % (len(data) - 1))
        f.write('#include "progrom.h"\n\nconst uint8_t progrom[0x%04X] = {\n' % len(data))
        for a in range(0, len(data), 16):
            f.write("    /* %04X */ %s,\n" % (a, ", ".join("0x%02X" % b for b in data[a:a + 16])))
        f.write("};\n")
    with open(os.path.join(CSRC, "rom_labels.h"), "w", encoding="utf-8", newline="\n") as f:
        f.write("/* rom_labels.h - GENERATED by c_src/tools/gen_roms.py from the listing's\n"
                " * named labels (../disasm/build/program_refs.json) - do not edit.\n"
                " * R_Name = ROM address of the label Name in clowns_program_rom.asm. */\n"
                "#ifndef ROM_LABELS_H\n#define ROM_LABELS_H\n\n")
        for a, name in sorted(labels.items()):
            f.write("#define R_%-24s 0x%s\n" % (name, a))
        f.write("\n#endif /* ROM_LABELS_H */\n")
    print("wrote progrom.c/.h (%d bytes), rom_labels.h (%d labels)" % (len(data), len(labels)))


if __name__ == "__main__":
    main()
