#!/usr/bin/env python3
"""Generate state_defs.h (RAM symbol aliases) from ../disasm/clowns_defines.asm.

Same rule as the Tempest port's tools/gen_state.py (the defines files share the
";---[ Section ]---" layout):

  * every .alias outside "Constants" and the port sections becomes an address
        #define A_NAME  0xADDR
  * aliases in the "Work RAM" sections also become the cell as an lvalue
        #define NAME    (g.ram[A_NAME - 0x2000])
  * "Constants" aliases are values:      #define K_NAME  0xVALUE
  * port aliases are port numbers:       #define P_NAME  0xNN
    (translated code reaches the ports through the hw_* seam, hw.h)

Rerun after regenerating the disassembly:   python c_src/tools/gen_state.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CSRC = os.path.normpath(os.path.join(HERE, ".."))
ROOT = os.path.normpath(os.path.join(CSRC, ".."))
SRC = os.path.join(ROOT, "disasm", "clowns_defines.asm")
OUT = os.path.join(CSRC, "state_defs.h")

RAM_BASE = 0x2000
CONST_SECTION = "Constants"
PORT_SECTIONS = ("Input ports", "Output ports")

SECTION_RE = re.compile(r"^;-*\[\s*(.*?)\s*\]-*$")
ALIAS_RE = re.compile(r"^\.alias\s+(\w+)\s+\$([0-9A-Fa-f]+)\s*(?:;(.*))?$")


def parse(path):
    """[(section, name, value, comment)] in file order."""
    out, section = [], ""
    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            m = SECTION_RE.match(line)
            if m:
                section = m.group(1)
                continue
            m = ALIAS_RE.match(line)
            if m:
                out.append((section, m.group(1), int(m.group(2), 16), (m.group(3) or "").strip()))
    return out


def ccomment(text):
    return text.replace("*/", "* /")


def main():
    if not os.path.exists(SRC):
        sys.exit("gen_state: missing %s (run disasm/gen_from_roms.py first)" % SRC)
    aliases = parse(SRC)
    nram = nconst = naddr = nport = 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        w = f.write
        w("/* state_defs.h - GENERATED by c_src/tools/gen_state.py from\n"
          " * ../disasm/clowns_defines.asm - do not edit by hand.\n"
          " *\n"
          " * A_NAME = CPU address of an alias.  NAME = the RAM cell as an lvalue\n"
          " * (Work RAM sections).  K_NAME = a Constants value.  P_NAME = a port number. */\n\n")
        w("#ifndef STATE_DEFS_H\n#define STATE_DEFS_H\n")
        cur = None
        for sec, name, val, cmt in aliases:
            if sec != cur:
                w("\n/* ---- %s ---- */\n" % sec)
                cur = sec
            c = ("  /* %s */" % ccomment(cmt)) if cmt else ""
            if sec == CONST_SECTION:
                w("#define K_%-16s 0x%02X%s\n" % (name, val, c))
                nconst += 1
            elif sec in PORT_SECTIONS:
                w("#define P_%-16s 0x%02X%s\n" % (name, val, c))
                nport += 1
            else:
                w("#define A_%-16s 0x%04X%s\n" % (name, val, c))
                naddr += 1
                if sec.startswith("Work RAM"):
                    w("#define %-18s (g.ram[A_%s - 0x%04X])\n" % (name, name, RAM_BASE))
                    nram += 1
        w("\n#endif /* STATE_DEFS_H */\n")
    print("wrote %s (%d addresses, %d RAM cells, %d constants, %d ports)"
          % (os.path.normpath(OUT), naddr, nram, nconst, nport))


if __name__ == "__main__":
    main()
