/* progrom.h - GENERATED by c_src/tools/gen_roms.py - do not edit. */
#ifndef PROGROM_H
#define PROGROM_H
#include <stdint.h>
#define PROGROM_SIZE 0x1800
extern const uint8_t progrom[0x1800]; /* program ROM $0000-$17FF */
#endif
