/* state_defs.h - GENERATED by c_src/tools/gen_state.py from
 * ../disasm/clowns_defines.asm - do not edit by hand.
 *
 * A_NAME = CPU address of an alias.  NAME = the RAM cell as an lvalue
 * (Work RAM sections).  K_NAME = a Constants value.  P_NAME = a port number. */

#ifndef STATE_DEFS_H
#define STATE_DEFS_H

/* ---- Memory map ---- */
#define A_ProgramRom       0x0000  /* Through $17FF. Six 1K ROMs H G F E D C (clowns_program_rom.asm). */
#define A_WorkRam          0x2000  /* Through $23FF. Variables; the 8080 stack grows down from $2400. */
#define A_VideoRam         0x2400  /* Through $3FFF. 256 x 224 bitmap, 32 bytes per line, bit 0 = leftmost pixel. Address = $2400 + 32*Y + X/8. */
#define A_EmptyRomSpace    0x4000  /* Through $5FFF. The board's second ROM area, not fitted on Clowns: writes are ignored. A splatted clown sinking below line 223 is drawn into it. */
#define A_RamMirror        0x6000  /* Through $7FFF. $2000-$3FFF again (only 15 address bits are decoded). Not used. */

/* ---- Input ports ---- */
#define P_INP_PADDLE       0x00  /* IN0. Paddle position 0-255 of the player selected by OUT_MISC bit 1. */
#define P_INP_SWITCH       0x01  /* IN1, active low. b4 2-player start, b5 1-player start, b6 coin. */
#define P_INP_DIP          0x02  /* IN2. b0-b1 coinage (0 1C/1P, 1 1C/2P, 2 2C/2P, 3 2C/1P), b2-b3 bonus game (0 none, 9000, 11000, 13000), b4 balloon resets (0 each row, 1 all rows), b5 extra jump at 3000/4000, b6 jumps 3/4, b7 self test. */
#define P_INP_SHIFT        0x03  /* MB14241 shifter result: the last two bytes written, shifted by the count. */

/* ---- Output ports ---- */
#define P_OUT_SHIFT_AMT    0x01  /* MB14241 shift count (low 3 bits = X position within the byte). */
#define P_OUT_SHIFT_DATA   0x02  /* MB14241 shift data. */
#define P_OUT_MISC         0x03  /* b0 coin counter, b1 paddle select (1 = player 2). Shadow in OUT3_SHADOW. */
#define P_OUT_WATCHDOG     0x04  /* Any write clears the watchdog. */
#define P_OUT_TONE_LO      0x05  /* Tone generator: b0 tone enable, b1-b5 low five bits of the period. */
#define P_OUT_TONE_HI      0x06  /* Tone generator: b0-b5 high six bits of the period. */
#define P_OUT_SOUND        0x07  /* b0 pop (bottom row), b1 pop (middle row), b2 pop (top row), b3 sound enable, b4 springboard hit, b5 miss (rising edge). */

/* ---- Work RAM: script, scores, timers ---- */
#define A_SCRIPT_PTR       0x2000  /* 2 bytes. Game script program counter (the interpreter is MainLoop). */
#define SCRIPT_PTR         (g.ram[A_SCRIPT_PTR - 0x2000])
#define A_SECOND_PRESCALE  0x2002  /* Counts 30 odd frames down to one TMR_TIMEOUT tick (about a second). */
#define SECOND_PRESCALE    (g.ram[A_SECOND_PRESCALE - 0x2000])
#define A_TIMEOUT_PTR      0x2003  /* 2 bytes. Script address taken when TMR_TIMEOUT runs out (script TIMEOUT command). */
#define TIMEOUT_PTR        (g.ram[A_TIMEOUT_PTR - 0x2000])
#define A_GAME_ACTIVE      0x2005  /* 0 = attract mode, 1 = a game is being played. */
#define GAME_ACTIVE        (g.ram[A_GAME_ACTIVE - 0x2000])
#define A_COIN_SW_PREV     0x2006  /* Last coin switch state ($40 = down) for edge detection. */
#define COIN_SW_PREV       (g.ram[A_COIN_SW_PREV - 0x2000])
#define A_RNG_SEED         0x2007  /* 8-bit shift-register random number. */
#define RNG_SEED           (g.ram[A_RNG_SEED - 0x2000])
#define A_COINS            0x2009  /* Coins inserted and not yet spent. */
#define COINS              (g.ram[A_COINS - 0x2000])
#define A_COINS_PER_GAME   0x200A  /* Coins the current game cost; a bonus game adds this many back to COINS. */
#define COINS_PER_GAME     (g.ram[A_COINS_PER_GAME - 0x2000])
#define A_SCRIPT_HOLD      0x200B  /* Non-zero: an expired TMR_SCRIPT does not step the script past its WAIT. */
#define SCRIPT_HOLD        (g.ram[A_SCRIPT_HOLD - 0x2000])
#define A_TIMEOUT_HOLD     0x200C  /* Non-zero: an expired TMR_TIMEOUT does not jump to TIMEOUT_PTR. */
#define TIMEOUT_HOLD       (g.ram[A_TIMEOUT_HOLD - 0x2000])
#define A_FRAME_CTR        0x200D  /* Incremented each frame; bit 0 picks seesaw frame (even) or balloon frame (odd). */
#define FRAME_CTR          (g.ram[A_FRAME_CTR - 0x2000])
#define A_P1_SCORE         0x200E  /* 2 bytes. Player 1 score, BCD, high byte first. Shown with a fixed 0 appended (tens of points). */
#define P1_SCORE           (g.ram[A_P1_SCORE - 0x2000])
#define A_JUMPS_LEFT       0x2010  /* Jumps (lives) left, shown after JUMPS. */
#define JUMPS_LEFT         (g.ram[A_JUMPS_LEFT - 0x2000])
#define A_P2_SCORE         0x2011  /* 2 bytes. Player 2 score, same format as P1_SCORE. */
#define P2_SCORE           (g.ram[A_P2_SCORE - 0x2000])
#define A_PADDLE_POS       0x2013  /* Wanted seesaw X: the paddle (read at vblank when PADDLE_ENABLE) or the attract autopilot. */
#define PADDLE_POS         (g.ram[A_PADDLE_POS - 0x2000])
#define A_OUT3_SHADOW      0x2014  /* Copy of OUT_MISC: b0 coin counter, b1 paddle select. */
#define OUT3_SHADOW        (g.ram[A_OUT3_SHADOW - 0x2000])
#define A_HI_SCORE         0x2015  /* 2 bytes. High score, BCD, high byte first. Below $2040, so it survives the script CLEAR. */
#define HI_SCORE           (g.ram[A_HI_SCORE - 0x2000])
#define A_REFILL_PENDING   0x2017  /* Non-zero while a cleared row waits to be refilled: the row's Y (each-row mode) or 1 (all rows). */
#define REFILL_PENDING     (g.ram[A_REFILL_PENDING - 0x2000])
#define A_REFILL_ROW_PTR   0x2018  /* 2 bytes. Balloon row (or first row) that TMR_REFILL will refill. */
#define REFILL_ROW_PTR     (g.ram[A_REFILL_ROW_PTR - 0x2000])
#define A_NEXT_PLAYER      0x201A  /* Player for the next turn; ClearRamTop copies it to PLAYER. */
#define NEXT_PLAYER        (g.ram[A_NEXT_PLAYER - 0x2000])
#define A_NEXT_JUMPS_LEFT  0x201B  /* Jumps left for the next turn; ClearRamTop copies it to JUMPS_LEFT. */
#define NEXT_JUMPS_LEFT    (g.ram[A_NEXT_JUMPS_LEFT - 0x2000])
#define A_SPEED_LEVEL      0x201C  /* 0-4. Launch speed is SPEED_LEVEL+5; goes up every third launch. */
#define SPEED_LEVEL        (g.ram[A_SPEED_LEVEL - 0x2000])
#define A_TUNE_TEMPO       0x201D  /* Frames per beat of the tune being played. */
#define TUNE_TEMPO         (g.ram[A_TUNE_TEMPO - 0x2000])
#define A_TUNE_TICKS       0x201E  /* Frames left in the current beat. */
#define TUNE_TICKS         (g.ram[A_TUNE_TICKS - 0x2000])
#define A_TUNE_BEATS       0x201F  /* Beats left in the current note. */
#define TUNE_BEATS         (g.ram[A_TUNE_BEATS - 0x2000])
#define A_TUNE_GAP         0x2020  /* Frames of silence owed before the next note. */
#define TUNE_GAP           (g.ram[A_TUNE_GAP - 0x2000])
#define A_TUNE_ON          0x2021  /* Non-zero: PlayTune runs. */
#define TUNE_ON            (g.ram[A_TUNE_ON - 0x2000])
#define A_TUNE_PTR         0x2022  /* 2 bytes. Next byte of the tune. */
#define TUNE_PTR           (g.ram[A_TUNE_PTR - 0x2000])
#define A_JUMPS_AGAIN      0x2024  /* Non-zero: the player earned an extra jump; the turn does not pass and no jump is used. */
#define JUMPS_AGAIN        (g.ram[A_JUMPS_AGAIN - 0x2000])
#define A_PREV_BONUS_GAME  0x2025  /* BONUS_GAME of the game that just ended; a game played on a bonus cannot win another. */
#define PREV_BONUS_GAME    (g.ram[A_PREV_BONUS_GAME - 0x2000])
#define A_TMR_TIMEOUT      0x2028  /* Slow timer (seconds). Expiry -> EVT_TIMEOUT b0 -> script jumps to TIMEOUT_PTR. */
#define TMR_TIMEOUT        (g.ram[A_TMR_TIMEOUT - 0x2000])
#define A_TMR_SCRIPT       0x2029  /* 30 Hz timers $2029-$2030 (TickTimers). This one: script DELAY; expiry steps past the WAIT. */
#define TMR_SCRIPT         (g.ram[A_TMR_SCRIPT - 0x2000])
#define A_TMR_SOUND_OFF    0x202A  /* Expiry ends the pop / hit / miss sound (OUT_SOUND = $08). */
#define TMR_SOUND_OFF      (g.ram[A_TMR_SOUND_OFF - 0x2000])
#define A_TMR_WALK         0x202B  /* Expiry advances the walk animation of the clown being served. */
#define TMR_WALK           (g.ram[A_TMR_WALK - 0x2000])
#define A_TMR_SERVE_JUMP   0x202C  /* Expiry makes the served clown jump off its ledge. */
#define TMR_SERVE_JUMP     (g.ram[A_TMR_SERVE_JUMP - 0x2000])
#define A_TMR_GRAVITY      0x202D  /* Expiry adds 1 to the flyer's Y velocity; reloaded from GRAVITY_PERIOD. */
#define TMR_GRAVITY        (g.ram[A_TMR_GRAVITY - 0x2000])
#define A_TMR_SPLAT        0x202E  /* Expiry steps the splat animation. */
#define TMR_SPLAT          (g.ram[A_TMR_SPLAT - 0x2000])
#define A_TMR_HIT_LOCKOUT  0x202F  /* While running, sprite contact is ignored (after a launch or a pop). No expiry action. */
#define TMR_HIT_LOCKOUT    (g.ram[A_TMR_HIT_LOCKOUT - 0x2000])
#define A_TMR_REFILL       0x2030  /* Expiry refills the cleared balloon row(s). */
#define TMR_REFILL         (g.ram[A_TMR_REFILL - 0x2000])
#define A_TMR_COIN_CTR     0x2031  /* 30 Hz timers $2031-$2033. This one: expiry ends the coin counter pulse. */
#define TMR_COIN_CTR       (g.ram[A_TMR_COIN_CTR - 0x2000])
#define A_TMR_TUMBLE       0x2032  /* Paces the flyer's tumble frames. No expiry action; polled by AnimateFlyer. */
#define TMR_TUMBLE         (g.ram[A_TMR_TUMBLE - 0x2000])
#define A_TMR_FREEZE       0x2033  /* Expiry ends the bonus freeze and erases the BONUS message. */
#define TMR_FREEZE         (g.ram[A_TMR_FREEZE - 0x2000])

/* ---- Work RAM: balloon rows ---- */
#define A_P1_ROW_TOP       0x2040  /* 36 bytes. Balloon rows: 12 balloons x (state b7 = present, X, Y). Player 1 top row (Y $24, 100 points). */
#define P1_ROW_TOP         (g.ram[A_P1_ROW_TOP - 0x2000])
#define A_P2_ROW_TOP       0x2064  /* 36 bytes. Player 2 top row. Every player 2 row is P2_OFFSET above player 1's. */
#define P2_ROW_TOP         (g.ram[A_P2_ROW_TOP - 0x2000])
#define A_P1_ROW_MID       0x2088  /* 36 bytes. Player 1 middle row (Y $38, 50 points). */
#define P1_ROW_MID         (g.ram[A_P1_ROW_MID - 0x2000])
#define A_P2_ROW_MID       0x20AC  /* 36 bytes. Player 2 middle row. */
#define P2_ROW_MID         (g.ram[A_P2_ROW_MID - 0x2000])
#define A_P1_ROW_BOT       0x20D0  /* 36 bytes. Player 1 bottom row (Y $4E, 20 points). */
#define P1_ROW_BOT         (g.ram[A_P1_ROW_BOT - 0x2000])
#define A_P2_ROW_BOT       0x20F4  /* 36 bytes. Player 2 bottom row. */
#define P2_ROW_BOT         (g.ram[A_P2_ROW_BOT - 0x2000])

/* ---- Work RAM: seesaw, players, clown objects ---- */
#define A_SEESAW_STATE     0x2118  /* b7 on screen, b6 tipping, b5 right end down (clown waits on the right), b0-b3 picture 0-4. */
#define SEESAW_STATE       (g.ram[A_SEESAW_STATE - 0x2000])
#define A_SEESAW_DRAWN_X   0x2119  /* X the seesaw was last drawn at (erased from here next time). */
#define SEESAW_DRAWN_X     (g.ram[A_SEESAW_DRAWN_X - 0x2000])
#define A_P1_EXTRA_JUMP    0x211B  /* Non-zero once player 1 has been given the extra jump. */
#define P1_EXTRA_JUMP      (g.ram[A_P1_EXTRA_JUMP - 0x2000])
#define A_P2_EXTRA_JUMP    0x211C  /* Same for player 2. */
#define P2_EXTRA_JUMP      (g.ram[A_P2_EXTRA_JUMP - 0x2000])
#define A_PLAYER           0x211D  /* $00 = player 1, $FF = player 2. */
#define PLAYER             (g.ram[A_PLAYER - 0x2000])
#define A_TWO_PLAYERS      0x211E  /* Non-zero in a two-player game. */
#define TWO_PLAYERS        (g.ram[A_TWO_PLAYERS - 0x2000])
#define A_BONUS_GAME       0x211F  /* Non-zero once the bonus game has been awarded in this game. */
#define BONUS_GAME         (g.ram[A_BONUS_GAME - 0x2000])
#define A_CLOWN_A          0x2180  /* 64 bytes. Clown object (see the CL_ offsets). */
#define CLOWN_A            (g.ram[A_CLOWN_A - 0x2000])
#define A_CLOWN_B          0x21C0  /* 64 bytes. Second clown object. */
#define CLOWN_B            (g.ram[A_CLOWN_B - 0x2000])

/* ---- Work RAM: text buffer and game state ---- */
#define A_TEXT_BUF         0x2200  /* 15 bytes. Characters of the score line: player 1 score (5), jumps left (1), player 2 score (5). */
#define TEXT_BUF           (g.ram[A_TEXT_BUF - 0x2000])
#define A_BONUS_BUF        0x220F  /* 5 bytes. Characters of the row bonus value. */
#define BONUS_BUF          (g.ram[A_BONUS_BUF - 0x2000])
#define A_EVT_TIMEOUT      0x2219  /* b0 set by the interrupt when TMR_TIMEOUT ran out; taken by CheckTimeout. */
#define EVT_TIMEOUT        (g.ram[A_EVT_TIMEOUT - 0x2000])
#define A_EVT_TIMERS       0x221A  /* Expiry bits for $2029-$2030 (b7 = $2029 ... b0 = $2030); taken by RunTimerEvents. */
#define EVT_TIMERS         (g.ram[A_EVT_TIMERS - 0x2000])
#define A_EVT_TIMERS2      0x221B  /* Expiry bits for $2031-$2033 (b2 = $2031 ... b0 = $2033); taken by RunTimerEvents2. */
#define EVT_TIMERS2        (g.ram[A_EVT_TIMERS2 - 0x2000])
#define A_SEESAW_X         0x221D  /* Seesaw X: PADDLE_POS limited to $D7. */
#define SEESAW_X           (g.ram[A_SEESAW_X - 0x2000])
#define A_SERVE_REQUEST    0x221E  /* Non-zero: ServeClown sets up both clowns for a new jump. */
#define SERVE_REQUEST      (g.ram[A_SERVE_REQUEST - 0x2000])
#define A_SERVING          0x221F  /* Non-zero while the served clown walks on its ledge (no gravity, no tumbling). */
#define SERVING            (g.ram[A_SERVING - 0x2000])
#define A_WALK_PHASE       0x2220  /* 0-3, steps the walk picture +1 +1 -1 -1. */
#define WALK_PHASE         (g.ram[A_WALK_PHASE - 0x2000])
#define A_GRAVITY_PERIOD   0x2221  /* TMR_GRAVITY reload: 5 in attract, 4 at the start of a jump, up to 8. */
#define GRAVITY_PERIOD     (g.ram[A_GRAVITY_PERIOD - 0x2000])
#define A_GRAVITY_STEP_CTR 0x2222  /* Every 2nd launch raises GRAVITY_PERIOD. */
#define GRAVITY_STEP_CTR   (g.ram[A_GRAVITY_STEP_CTR - 0x2000])
#define A_SPLAT_CTR        0x2223  /* Splat pictures left. */
#define SPLAT_CTR          (g.ram[A_SPLAT_CTR - 0x2000])
#define A_FLYER_PTR        0x2224  /* 2 bytes. Clown object in the air (or being served). */
#define FLYER_PTR          (g.ram[A_FLYER_PTR - 0x2000])
#define A_RIDER_PTR        0x2226  /* 2 bytes. Clown object standing on the seesaw. */
#define RIDER_PTR          (g.ram[A_RIDER_PTR - 0x2000])
#define A_ERASE_MODE       0x2228  /* OR-ed into the flyer's state when it is drawn: $40 put the saved background back, $20 blank the box. */
#define ERASE_MODE         (g.ram[A_ERASE_MODE - 0x2000])
#define A_HIT_ROW          0x2229  /* Row of the balloon just popped: 0 bottom, 1 middle, 2 top. */
#define HIT_ROW            (g.ram[A_HIT_ROW - 0x2000])
#define A_START1_DOWN      0x222A  /* $20 while the 1-player start button is down. */
#define START1_DOWN        (g.ram[A_START1_DOWN - 0x2000])
#define A_START2_DOWN      0x222B  /* $10 while the 2-player start button is down. */
#define START2_DOWN        (g.ram[A_START2_DOWN - 0x2000])
#define A_PLAYFIELD_ON     0x222C  /* Non-zero: the floor and the four ledges are redrawn every main loop pass. */
#define PLAYFIELD_ON       (g.ram[A_PLAYFIELD_ON - 0x2000])
#define A_PADDLE_ENABLE    0x222D  /* Non-zero: the vblank interrupt copies the paddle to PADDLE_POS. */
#define PADDLE_ENABLE      (g.ram[A_PADDLE_ENABLE - 0x2000])
#define A_AUTOPILOT        0x222E  /* Non-zero: attract mode steers the seesaw under the flyer. */
#define AUTOPILOT          (g.ram[A_AUTOPILOT - 0x2000])
#define A_DIGIT_INDEX      0x2230  /* Which character of TEXT_BUF DrawNextDigit shows next. */
#define DIGIT_INDEX        (g.ram[A_DIGIT_INDEX - 0x2000])
#define A_FLYER_HIGH       0x2231  /* Non-zero when the flyer is above Y $50: it is then updated at mid-screen, else at vblank. */
#define FLYER_HIGH         (g.ram[A_FLYER_HIGH - 0x2000])
#define A_FREEZE           0x2232  /* Non-zero: flyer and balloons stand still (bonus message). */
#define FREEZE             (g.ram[A_FREEZE - 0x2000])
#define A_FREEZE_REQ       0x2233  /* Copied to FREEZE after the flyer's next update. */
#define FREEZE_REQ         (g.ram[A_FREEZE_REQ - 0x2000])
#define A_CONTACT_ROW      0x2234  /* Set by the interrupt: 1 + sprite row where the flyer first touched something; cleared by HandleContact. */
#define CONTACT_ROW        (g.ram[A_CONTACT_ROW - 0x2000])
#define A_BALLOON_PHASE    0x2235  /* 0-5, which entry of BalloonTasks runs this odd frame. */
#define BALLOON_PHASE      (g.ram[A_BALLOON_PHASE - 0x2000])
#define A_SPEED_STEP_CTR   0x2236  /* Every 3rd launch raises SPEED_LEVEL. */
#define SPEED_STEP_CTR     (g.ram[A_SPEED_STEP_CTR - 0x2000])
#define A_REBOUND_STEP_CTR 0x2237  /* Every 4th launch raises REBOUND_SPEED. */
#define REBOUND_STEP_CTR   (g.ram[A_REBOUND_STEP_CTR - 0x2000])
#define A_REBOUND_SPEED    0x2238  /* 0-4. Downward speed given to a flyer that pops a balloon on the way up. */
#define REBOUND_SPEED      (g.ram[A_REBOUND_SPEED - 0x2000])

/* ---- Constants ---- */
#define K_CL_STATE         0x00  /* b7 in use, b6 put back the saved background before the next draw, b5 blank the old box, b4 slow (moves every 4th update), b3 splatted, b0-b2 slow tick. */
#define K_CL_FRAME         0x01  /* Picture number, index into ClownPictures. */
#define K_CL_XVEL          0x02  /* Added to X at every update. */
#define K_CL_X             0x03  /* X, 0-$F1. */
#define K_CL_YVEL          0x04  /* Added to Y at every update. */
#define K_CL_Y             0x05  /* Y of the top of the picture. */
#define K_CL_SCREEN        0x06  /* Video RAM address the picture was drawn at (2 bytes). */
#define K_CL_ROWS          0x08  /* Rows drawn. */
#define K_CL_WIDTH         0x09  /* Screen bytes per row: picture bytes + 1 for the shift (3 for the flyer, 2 for the rider). */
#define K_CL_SAVED         0x0A  /* Background bytes saved while drawing, CL_WIDTH per row. */
#define K_P2_OFFSET        0x24  /* Player 2's balloon row = player 1's + $24 (12 balloons x 3 bytes). */

#endif /* STATE_DEFS_H */
